# Site
name: 'Using Primavera'
description: >- 
  Oracle Primavera P6, Unifier and Oracle BI Publisher
logo: 'assets/images/logo.png' 
favicon: 'assets/images/favicon.png'
url: 'https://usingprimavera.com'
baseurl: ''
disqus: ''
email: 'barrie@usingprimavera.com'
# Newsletter
tinyletter: true # To enable the TinyLetter form, use the value true. To turn off use the value false.
tinyletter-identifier: 'https://tinyletter.com/UsingPrimavera' # Add your TinyLetter subscribe form.
tinyletter-title: 'Get Newsletter Updates'
tinyletter-description: 'Subscribe to our newsletter to hear what we have been writing about.'

include: ["_pages"]
permalink: pretty

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

authors:
    barrie:
      name:           Barrie
      site:           https://usingprimavera.com
      avatar:         assets/images/avatar_barrie.jpg
      bio:            ""
      email:          barrie@usingprimavera.com
      twitter:        https://twitter.com/usingprimavera
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Barrie
      avatar: /assets/images/avatar_barrie.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

##############################################################################

#google map api key

map: 'AIzaSyA7nx22ZmINYk9TGiXDEXGVxghC43Ox6qA'

# jekyll_compose
jekyll_compose:
  default_front_matter:
    drafts:
      description:
      author: Barrie
      image:
    posts:
      description:
      author: Barrie
      image:

# octopress
# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: false

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

