# Site
title: Using Primavera
tagline: Oracle BI Publisher, P6 and Unifier working together.
name: 'Using Primavera'
description: A blog dedicated to helping you get the practical information needed to use Oracle BI Publisher with P6 and Unifier. However, it will be more than just reports.
logo: 'assets/images/logo.png' 
favicon: 'assets/images/favicon.png'
url: 'https://usingprimavera.com'
baseurl: ''
disqus: ''
email: 'barrie@usingprimavera.com'
# Newsletter
tinyletter: true # To enable the TinyLetter form, use the value true. To turn off use the value false.
tinyletter-identifier: 'https://tinyletter.com/UsingPrimavera' # Add your TinyLetter subscribe form.
tinyletter-title: 'Get Newsletter Updates'
tinyletter-description: 'Subscribe to our newsletter to hear what we have been writing about.'

include: ["_pages"]
permalink: /:slug/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  


author:
  name: Barrie Callender
  twitter: usingprimavera
  url: https://www.linkedin.com/in/barriecallender/
  image: assets/images/barrie_callender_400x400.jpg 
twitter:
  username: usingprimavera
  card: summary_large_image
social:
  name: Barrie Callender
  links:
    - https://twitter.com/usingprimavera
    - https://www.facebook.com/usingprimavera
    - https://www.linkedin.com/in/barriecallender/
    - https://github.com/UsingPrimavera
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Barrie
      avatar: /assets/images/avatar_barrie.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

##############################################################################

#google map api key

map: 'AIzaSyA7nx22ZmINYk9TGiXDEXGVxghC43Ox6qA'

# jekyll_compose
jekyll_compose:
  default_front_matter:
    drafts:
      description:
      author: Barrie
      image:
    posts:
      description:
      author: Barrie
      image:

# octopress
# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: false

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

