title: Using Primavera
description: Slowly documenting what I have learned about using primavera P6, Gateway, Unifier and Oracle Analytics Publisher.
theme: just-the-docs

url: https://usingprimavera.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

