# Site
name: 'Using Primavera'
description: >- 
  This site is aboout the work I undertake using Primavera P6, Primavera P6 EPPM, 
  Primavera Unifier, Primavera Gateway, Primavera Data Warehouse and Primavera Analytics.
logo: 'assets/images/logo.png' 
favicon: 'assets/images/favicon.png'
baseurl: ''
disqus: ''
email: 'barrie@usingprimavera.com'
mailchimp-list: ''

include: ["_pages"]
permalink: pretty

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    barrie:
      name:           Barrie
      site:           https://usingprimavera.com
      avatar:         assets/images/avatar_barrie.jpg
      bio:            ""
      email:          barrie@usingprimavera.com
      twitter:        https://twitter.com/usingprimavera
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: barrie
      avatar: /assets/images/avatar_barrie.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

##############################################################################

#google map api key

map: 'AIzaSyA7nx22ZmINYk9TGiXDEXGVxghC43Ox6qA'
